const prefix = 'app_Authentication';

export const AUTHENTICATION_REQUEST = `${prefix}/AUTHENTICATION_REQUEST`;
export const AUTHENTICATION_REQUEST_SUCCESS = `${prefix}/AUTHENTICATION_REQUEST_SUCCESS`;
export const AUTHENTICATION_REQUEST_FAILURE = `${prefix}/AUTHENTICATION_REQUEST_FAILURE`;
// export const SET_PAGE_ORDER_LOADING = `${prefix}/SET_PAGE_ORDER_LOADING`;
